name: Java CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build and test
      run: mvn clean install

  build_and_publish:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      shell: bash
      run: mvn clean package -Djpackage.profile=true

    - name: Install libfuse2
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2

    - name: Create AppImage
      working-directory: dist
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        ./appimagetool-x86_64.AppImage Fribok

    - name: Test AppImage
      run: |
        chmod +x dist/Fribok-x86_64.AppImage
        ./dist/Fribok-x86_64.AppImage --version

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fribok-linux
        path: dist/*
